{
    "imageDivider": {
        "2024-01-30 12:28:34": {
            "ExceptionName": "Telegram server says - Internal Server Error",
            "Traceback": [
                "Traceback (most recent call last):",
                "  File \"H:\\icreo\\lol\\bot\\main.py\", line 215, in Step2",
                "    await bot.send_photo(data[\"idChat\"], photo=BufferedInputFile(image_buffer.getvalue(), filename='photo.png'), caption=\"*\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0430\u0435\u0442\u0435 \u0440\u0430\u0437\u0440\u0435\u0437\u043a\u0443?*\", reply_markup=markups.Accept(), parse_mode=\"Markdown\")",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\bot.py\", line 2764, in send_photo",
                "    return await self(call, request_timeout=request_timeout)",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\bot.py\", line 432, in __call__",
                "    return await self.session(self, method, timeout=request_timeout)",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\base.py\", line 257, in __call__",
                "    return cast(TelegramType, await middleware(bot, method))",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\aiohttp.py\", line 175, in make_request",
                "    response = self.check_response(",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\base.py\", line 134, in check_response",
                "    raise TelegramServerError(method=method, message=description)",
                "aiogram.exceptions.TelegramServerError: Telegram server says - Internal Server Error"
            ]
        },
        "2024-06-25 20:26:26": {
            "ExceptionName": "Telegram server says - Bad Request: message to edit not found",
            "Traceback": [
                "Traceback (most recent call last):",
                "  File \"H:\\icreo\\lol\\bot\\main.py\", line 181, in Cutter",
                "    await bot.edit_message_text(text=f\"_\u041e\u0441\u0442\u0430\u043b\u043e\u0441\u044c \u0441\u0435\u043a\u0443\u043d\u0434\u043e\u0447\u043a\u0430._ \\n*\u041f\u0440\u043e\u0433\u0440\u0435\u0441\u0441: 100%*\",",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\bot.py\", line 1475, in edit_message_text",
                "    return await self(call, request_timeout=request_timeout)",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\bot.py\", line 432, in __call__",
                "    return await self.session(self, method, timeout=request_timeout)",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\base.py\", line 257, in __call__",
                "    return cast(TelegramType, await middleware(bot, method))",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\aiohttp.py\", line 175, in make_request",
                "    response = self.check_response(",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\base.py\", line 120, in check_response",
                "    raise TelegramBadRequest(method=method, message=description)",
                "aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message to edit not found"
            ]
        },
        "2024-06-26 20:03:12": {
            "ExceptionName": "Telegram server says - Bad Request: message to edit not found",
            "Traceback": [
                "Traceback (most recent call last):",
                "  File \"H:\\icreo\\lol\\bot\\main.py\", line 181, in Cutter",
                "    await bot.edit_message_text(text=f\"_\u041e\u0441\u0442\u0430\u043b\u043e\u0441\u044c \u0441\u0435\u043a\u0443\u043d\u0434\u043e\u0447\u043a\u0430._ \\n*\u041f\u0440\u043e\u0433\u0440\u0435\u0441\u0441: 100%*\",",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\bot.py\", line 1475, in edit_message_text",
                "    return await self(call, request_timeout=request_timeout)",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\bot.py\", line 432, in __call__",
                "    return await self.session(self, method, timeout=request_timeout)",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\base.py\", line 257, in __call__",
                "    return cast(TelegramType, await middleware(bot, method))",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\aiohttp.py\", line 175, in make_request",
                "    response = self.check_response(",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\base.py\", line 120, in check_response",
                "    raise TelegramBadRequest(method=method, message=description)",
                "aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message to edit not found"
            ]
        },
        "2024-06-26 20:20:33": {
            "ExceptionName": "Telegram server says - Bad Request: message to edit not found",
            "Traceback": [
                "Traceback (most recent call last):",
                "  File \"H:\\icreo\\lol\\bot\\main.py\", line 181, in Cutter",
                "    await bot.edit_message_text(text=f\"_\u041e\u0441\u0442\u0430\u043b\u043e\u0441\u044c \u0441\u0435\u043a\u0443\u043d\u0434\u043e\u0447\u043a\u0430._ \\n*\u041f\u0440\u043e\u0433\u0440\u0435\u0441\u0441: 100%*\",",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\bot.py\", line 1475, in edit_message_text",
                "    return await self(call, request_timeout=request_timeout)",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\bot.py\", line 432, in __call__",
                "    return await self.session(self, method, timeout=request_timeout)",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\base.py\", line 257, in __call__",
                "    return cast(TelegramType, await middleware(bot, method))",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\aiohttp.py\", line 175, in make_request",
                "    response = self.check_response(",
                "  File \"C:\\Users\\909090\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\aiogram\\client\\session\\base.py\", line 120, in check_response",
                "    raise TelegramBadRequest(method=method, message=description)",
                "aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message to edit not found"
            ]
        }
    }
}